# Generated by Django 5.2.3 on 2025-07-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Сумма оплаты"
            ),
        ),
    ]
