# Generated by Django 5.2.3 on 2025-07-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Статус платежа",
            ),
        ),
    ]
