[tool.poetry]
name = "homework-module-8"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.3"
djangorestframework = "^3.16.0"
psycopg2 = "^2.9.10"
python-dotenv = "^1.1.0"
pillow = "^11.2.1"
django-stubs = "^5.2.0"
djangorestframework-stubs = "^3.16.0"
django-filter = "^25.1"
djangorestframework-simplejwt = "^5.5.0"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.2.0"
black = "^25.1.0"
isort = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
exclude = '''
(
  /(
      \.git
  )/
)
'''

[tool.isort]
line_length = 79
multi_line_output = 5
