# Generated by Django 5.2.3 on 2025-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Курс"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Урок"
            ),
        ),
    ]
