# Generated by Django 5.2.3 on 2025-06-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_title_alter_lesson_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Урок"),
        ),
    ]
