# Generated by Django 5.2.3 on 2025-07-01 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_video",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        message="Некорректный URL. Требуется HTTPS-ссылка.",
                        schemes=["https"],
                    )
                ],
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
