# Generated by Django 5.2.3 on 2025-07-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Стоимость курса"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Стоимость урока"
            ),
        ),
    ]
