# Generated by Django 5.2.3 on 2025-07-30 10:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_course_amount_lesson_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    7,
                    30,
                    10,
                    53,
                    56,
                    198466,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
