# Generated by Django 5.2.3 on 2025-07-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
