# Generated by Django 5.2.3 on 2025-07-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_alter_course_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="notification_task_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID задачи уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
